make __zert-align-version respect optional pin argument

diff --git a/lib/__zert-align-version b/lib/__zert-align-version
--- a/lib/__zert-align-version
+++ b/lib/__zert-align-version
@@ -25,13 +25,24 @@ __zert-align-version() {
     fi
     
     # Check lockfile for plugin hash
-    if [[ -n "$plugin_pin" ]]; then
-        local lockfile_hash="$plugin_pin"
-    else
-        local lockfile_hash=$(grep "^\[$plugin_name\]=" "$ZERT_LOCKFILE" | cut -d'=' -f2)
-    fi
     
-    if [[ -n "$lockfile_hash" ]]; then
+    local lockfile_hash=$(grep "^\[$plugin_name\]=" "$ZERT_LOCKFILE" | cut -d'=' -f2)
+    if [[ -n "$plugin_pin" ]]; then
+        if [[ "$current_hash" != "$plugin_pin" ]]; then
+            find "$plugin_dir" -type f -name "*.zwc" -exec rm -f {} \;
+            git -C "$plugin_dir" checkout "$plugin_pin" 2>/dev/null || {
+                __zert-log error GIT_CHECKOUT_FAILED "Failed to checkout $plugin_pin for $plugin_name"
+                return 1
+            }
+        fi
+        if [[ -n "$lockfile_hash" ]]; then
+            if [[ "$plugin_pin" != "$lockfile_hash" ]]; then
+                sed -i "s/^\(\[$plugin_name\]=\).*/\1$plugin_pin/" "$ZERT_LOCKFILE"
+            fi
+        else
+            echo "[$plugin_name]=$plugin_pin" >> "$ZERT_LOCKFILE"
+        fi
+    elif [[ -n "$lockfile_hash" ]]; then
         # If not aligned, remove *.zwc and checkout lockfile hash
         if [[ "$current_hash" != "$lockfile_hash" ]]; then
             find "$plugin_dir" -type f -name "*.zwc" -exec rm -f {} \;
